language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

services:
  - mongodb

before_script:
  - mongod --version
  - echo 'extension = "mongodb.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - ./scripts/travis
  - composer install

script: ./vendor/bin/phpunit
